version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093' #change to 9093 to access external from your windows host
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT #add aditional listener for external
      - KAFKA_CFG_LISTENERS=CLIENT://:9092,EXTERNAL://:9093 #9092 will be for other containers, 9093 for your windows client
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://kafka:9092,EXTERNAL://localhost:9093 #9092 will be for other containers, 9093 for your windows client
      - KAFKA_INTER_BROKER_LISTENER_NAME=CLIENT
    depends_on:
      - zookeeper

  minio:
    image: quay.io/minio/minio:RELEASE.2022-05-26T05-48-41Z
    hostname: minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - ./minio/data:/data
    env_file:
      - .env
    # environment:
    #   MINIO_ACCESS_KEY: minio
    #   MINIO_SECRET_KEY: minio123
    command: server --console-address ":9001" /data

  createbuckets:
    image: minio/mc
    links:
      - minio:minio
    depends_on:
      - minio
    volumes:
      - './scripts:/etc/minio'
    env_file:
      - .env
    entrypoint: /etc/minio/create_bucket.sh

  datagen:
    build:
      context: .
      dockerfile: datagen/Dockerfile
    env_file:
      - .env
    depends_on:
      - kafka

  pyspark:
    build:
      context: .
      dockerfile: connect/Dockerfile
    env_file:
      - .env
    depends_on:
      - datagen
      - kafka
