[project]
name = "atproto-firehose"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "confluent-kafka>=2.7.0",
    "pyspark==3.5.1",
    "typing>=3.10.0.0",
    "websockets>=14.1",
]
